import base64
import requests
from datetime import datetime, timezone


def _auth_header(email, api_token):
    token = base64.b64encode(f"{email}:{api_token}".encode()).decode()
    return {"Authorization": f"Basic {token}", "Content-Type": "application/json", "Accept": "application/json"}


def _build_page_body(scan):
    """Build Confluence storage-format HTML for a scan report."""
    from ..models import ScanResult

    results = scan.results.all()
    vulns = [r for r in results if r.result_type == "vulnerability"]
    web_checks = [r for r in results if r.result_type == "web_check"]
    ports = [r for r in results if r.result_type == "port"]

    sev_colors = {"critical": "#de350b", "high": "#ff8b00", "medium": "#ffab00", "low": "#0052cc", "info": "#6b778c"}

    def sev_badge(sev):
        color = sev_colors.get(sev, "#6b778c")
        return f'<strong><span style="color:{color}">{sev.upper()}</span></strong>'

    def vuln_rows():
        rows = ""
        for r in sorted(vulns, key=lambda x: ["critical","high","medium","low","info"].index(x.severity) if x.severity in ["critical","high","medium","low","info"] else 5):
            cve = f'<a href="https://nvd.nist.gov/vuln/detail/{r.cve_id}">{r.cve_id}</a>' if r.cve_id else "—"
            rows += f"""<tr>
              <td>{sev_badge(r.severity)}</td>
              <td>{r.title or '—'}</td>
              <td>{r.host or '—'}</td>
              <td>{cve}</td>
              <td>{r.cvss_score or '—'}</td>
              <td>{(r.description or '')[:200]}</td>
            </tr>"""
        return rows or "<tr><td colspan='6'>No vulnerabilities found.</td></tr>"

    def port_rows():
        rows = ""
        for r in ports:
            rows += f"<tr><td>{r.host or '—'}</td><td>{r.port}/{r.protocol}</td><td>{r.service or '—'}</td></tr>"
        return rows or "<tr><td colspan='3'>No open ports found.</td></tr>"

    def web_rows():
        rows = ""
        for r in web_checks:
            rows += f"<tr><td>{sev_badge(r.severity)}</td><td>{r.title or '—'}</td><td>{(r.description or '')[:200]}</td></tr>"
        return rows or "<tr><td colspan='3'>No web issues found.</td></tr>"

    completed = scan.completed_at.strftime("%Y-%m-%d %H:%M UTC") if scan.completed_at else "N/A"
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    return f"""
<h1>PwnBroker Security Scan Report</h1>
<p><strong>Scan:</strong> {scan.name}<br/>
<strong>Target:</strong> {scan.target.host}<br/>
<strong>Type:</strong> {scan.scan_type}<br/>
<strong>Completed:</strong> {completed}<br/>
<strong>Generated:</strong> {generated}</p>

<h2>Summary</h2>
<table>
<tr><th>Category</th><th>Count</th></tr>
<tr><td>Total Vulnerabilities</td><td>{len(vulns)}</td></tr>
<tr><td><span style="color:#de350b">Critical</span></td><td>{sum(1 for v in vulns if v.severity=='critical')}</td></tr>
<tr><td><span style="color:#ff8b00">High</span></td><td>{sum(1 for v in vulns if v.severity=='high')}</td></tr>
<tr><td><span style="color:#ffab00">Medium</span></td><td>{sum(1 for v in vulns if v.severity=='medium')}</td></tr>
<tr><td><span style="color:#0052cc">Low</span></td><td>{sum(1 for v in vulns if v.severity=='low')}</td></tr>
<tr><td>Open Ports</td><td>{len(ports)}</td></tr>
<tr><td>Web Issues</td><td>{len(web_checks)}</td></tr>
</table>

<h2>Vulnerabilities</h2>
<table>
<tr><th>Severity</th><th>Title</th><th>Host</th><th>CVE</th><th>CVSS</th><th>Description</th></tr>
{vuln_rows()}
</table>

<h2>Open Ports</h2>
<table>
<tr><th>Host</th><th>Port/Protocol</th><th>Service</th></tr>
{port_rows()}
</table>

<h2>Web Checks</h2>
<table>
<tr><th>Severity</th><th>Finding</th><th>Description</th></tr>
{web_rows()}
</table>

<p><em>Report generated by <strong>PwnBroker</strong> on {generated}</em></p>
"""


def publish_to_confluence(scan, cfg) -> dict:
    """
    Create or update a Confluence page for this scan.
    Returns {"ok": bool, "page_id": str|None, "page_url": str|None, "message": str}
    """
    headers = _auth_header(cfg.email, cfg.api_token)
    base = cfg.base_url.rstrip("/")
    api_base = f"{base}/wiki/rest/api/content"

    title = f"PwnBroker — {scan.name} — {scan.target.host}"
    body_value = _build_page_body(scan)

    # Check if we already published this scan (look for existing page)
    from ..models import ConfluencePage
    existing = ConfluencePage.query.filter_by(scan_id=scan.id).first()

    payload = {
        "type": "page",
        "title": title,
        "space": {"key": cfg.confluence_space_key},
        "body": {"storage": {"value": body_value, "representation": "storage"}},
    }

    if cfg.confluence_parent_page_id:
        payload["ancestors"] = [{"id": cfg.confluence_parent_page_id}]

    try:
        if existing and existing.page_id:
            # Update existing page — need current version number
            get_resp = requests.get(f"{api_base}/{existing.page_id}", headers=headers, timeout=15)
            if get_resp.status_code == 200:
                current_version = get_resp.json()["version"]["number"]
                payload["version"] = {"number": current_version + 1}
                payload["id"] = existing.page_id
                resp = requests.put(f"{api_base}/{existing.page_id}", json=payload, headers=headers, timeout=30)
            else:
                resp = requests.post(api_base, json=payload, headers=headers, timeout=30)
        else:
            resp = requests.post(api_base, json=payload, headers=headers, timeout=30)

        if resp.status_code in (200, 201):
            data = resp.json()
            page_id = data.get("id")
            page_url = f"{base}/wiki{data.get('_links', {}).get('webui', '')}"
            return {"ok": True, "page_id": page_id, "page_url": page_url, "message": "Published"}
        else:
            return {"ok": False, "page_id": None, "page_url": None,
                    "message": f"HTTP {resp.status_code}: {resp.text[:300]}"}

    except requests.exceptions.ConnectionError:
        return {"ok": False, "page_id": None, "page_url": None,
                "message": "Connection refused — check Atlassian base URL."}
    except Exception as e:
        return {"ok": False, "page_id": None, "page_url": None, "message": str(e)}
